name: build

on: [push, create]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: npm build
      run: npm run build
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: EhSyringe.zip
        path: release/EhSyringe.zip
    - name: publish to github release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact: release/EhSyringe.zip
    - name: publish to firefox store
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: npx shipit firefox dist
      env:
        WEXT_SHIPIT_FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
        WEXT_SHIPIT_FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
